#spring:
#  datasource:
#    url: jdbc:h2:./devdb
#    username: sa
#  jpa:
#    hibernate:
#      ddl-auto: update
spring:
  datasource:
    generate-unique-name: false
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none